### ISSUE TITLE
I am unable to connect using the same key on both the client and server

### ISSUE THREAD

**Issue by GingerLoaf** [KillaMaaki/Netcode.IO.NET#1]
I am trying to get a basic version of this server and client running and it seems that I am unable to do this.

In both my client and server, I have defined:

`    private static byte[] privateKey = new byte[]
    {
            0x60, 0x6a, 0xbe, 0x6e, 0xc9, 0x19, 0x10, 0xea,
            0x9a, 0x65, 0x62, 0xf6, 0x6f, 0x2b, 0x30, 0xe4,
            0x43, 0x71, 0xd6, 0x2c, 0xd1, 0x99, 0x27, 0x26,
            0x6b, 0x3c, 0x60, 0xf4, 0xb7, 0x15, 0xab, 0xa1
    };`

The server accepts this just fine and the client continues to throw exceptions while using the TokenFactory to generate a token using this private key. 

I have traced it down to AEAD_Chacha20_Poly1305.cs where the line `Array.Copy(mac, 0, outBuffer, len, macsize);` is executed. I am seeing that outBuffer is a byte array of 1024 length and len is also 1024, which would attempt to copy the 16 bytes from the mac array into outBuffer starting at index 1024 (out of bounds). Any help getting this running would be awesome :). I am excited to get things working!

This snippet of code reliably throws an index out of range exception every time I run it:

`        var tokenFactory = new TokenFactory(0, new byte[]
        {
                0x60, 0x6a, 0xbe, 0x6e, 0xc9, 0x19, 0x10, 0xea,
                0x9a, 0x65, 0x62, 0xf6, 0x6f, 0x2b, 0x30, 0xe4,
                0x43, 0x71, 0xd6, 0x2c, 0xd1, 0x99, 0x27, 0x26,
                0x6b, 0x3c, 0x60, 0xf4, 0xb7, 0x15, 0xab, 0xa1
        });
        var token = tokenFactory.GenerateConnectToken(new IPEndPoint[] { new IPEndPoint(IPAddress.Parse("127.0.0.1"), 5566) }, 30, 0, 1, new byte[0]);`

**Comment by GlaireDaggers** [comment]
Ah, yeah thanks for reporting it. Turns out my private connect token encryption was attempting to encrypt the entire 1024-byte input buffer into a 1024-byte output buffer (and the encryption method always requires the output buffer to be at least 16 bytes larger than the input length)
According to the spec it's only supposed to encrypt the first 1008 bytes of the input buffer, to leave from for the 16-byte hmac in the 1024-byte output buffer. I've pushed up a commit which should resolve this.
Do let me know if that resolves the issue :)

EDIT: Also note that for testing generating tokens on the client is fine, but in production it'd be better to have the server generate the tokens and keep its private key hidden from the client. If this is an application where players can host their own servers and connect to them using IP and endpoint, one option is to have the server randomize its key and then start up its own HTTP server instance which can serve up tokens to connecting clients. So then the client connects to the HTTP server at that IP address, retrieves a connect token (or not - you can build client rejection into this step too, for example to support banning players from servers, or build in password protection into this step), and then passes that connect token to the Connect method.

**Comment by Danila24ru** [comment]
Can you commit this fix to Unity plugin please.

**Comment by GingerLoaf** [comment]
I have verified that my problem is fixed with the new code. Thanks for the prompt update!
