### ISSUE TITLE
Client disconnect affects other clients on the server

### ISSUE THREAD

**Issue by gresolio** [KillaMaaki/Netcode.IO.NET#13]
Currently I am testing Netcode.IO.NET from commit f2b060e and I noticed strange thing: sometimes server stops sending keepAlive packets to all clients, and they go to "ConnectionTimedOut" state. This happens when one of the connected clients was disconnected.

As far as I understand, the reason was in EncryptionManager, and [this change](https://github.com/KillaMaaki/Netcode.IO.NET/commit/744e2442a59fcc5ee98ba1c6bfb7d29eea320a11#diff-0e3812d14a890d686cee1aaac727d169) fixes it (I have not tested completely yet). Have you also faced such issues? Or was it something different?

**Comment by GlaireDaggers** [comment]
The only time I encountered this issue was as a result of the bug you mentioned in the EncryptionManager, and that change did fix it. It was encountered during development of another project, and so far I have not encountered the same issue since.
When it *did* happen, it was because a typo caused several encryption keys to be removed from the encryption manager, not just for the client that disconnected, which in turn caused the keep alive message to not be sent because it could not find that client's encryption key.
I can try and give this some more tests, but in the meantime would it be at all possible for you to step through the core code when this happens to see if you can spot anything in case I can't reproduce it?

**Comment by gresolio** [comment]
Thanks, you confirmed my assumption. I will upgrade to latest commit with this fix and I will test it. If I can spot and reproduce anything suspicious, then I inform you.

Yes, it would be nice to add new UnitTest or extend some existing one to cover such a situation: multiple clients are connected to server, some of them should frequently disconnect/connect, and we are checking that other clients are still fine, they can succesfully tx/rx packets (no "ConnectionTimedOut" or something else not expected). At the moment "[TestClientServerMultipleClients](https://github.com/KillaMaaki/Netcode.IO.NET/blob/fa538a3aefed32ad674eca5cd40e8f2e9be90fc2/Netcode.IO.NET/Public/Tests.cs#L528)" is most similar to described scenario.
